name: "CI"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Run Hadolint"
        uses: "hadolint/hadolint-action@v2.1.0"
