name: "CI"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Run Hadolint"
        uses: "hadolint/hadolint-action@v2.1.0"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"
        with:
          platforms: "linux/arm64,linux/arm/v7"

      - name: "Set up Buildkit"
        id: "buildx-setup"
        uses: "docker/setup-buildx-action@v2"

      - name: "Build container image"
        uses: "docker/build-push-action@v3"
        with:
          context: "."
          push: false
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
